version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27018:27017"
    # volumes:
      # - mongodb_data:/data/db
      # - mongodb_config:/data/configdb
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
  medi-score-app:
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
# volumes:
# mongodb_data:
# mongodb_config:
